### ISSUE TITLE
'muri' can't parse 'youtu.be' uri

### ISSUE THREAD

**Issue by onesup** [bananastalktome/muri#1]
ruby-1.9.2-p180 :013 > m = Muri.parse "http://youtu.be/n3fzYOTxy5Q"
TypeError: can't convert Symbol into String
    from /Users/onesup/.rvm/gems/ruby-1.9.2-p180/gems/muri-1.1.6/lib/muri/base.rb:23:in `eval'
    from /Users/onesup/.rvm/gems/ruby-1.9.2-p180/gems/muri-1.1.6/lib/muri/base.rb:23:in`block (3 levels) in class:Muri'
    from /Users/onesup/.rvm/gems/ruby-1.9.2-p180/gems/muri-1.1.6/lib/muri/filters/youtube.rb:51:in `youtube_parse'
    from /Users/onesup/.rvm/gems/ruby-1.9.2-p180/gems/muri-1.1.6/lib/muri/base.rb:73:in`parse'
    from /Users/onesup/.rvm/gems/ruby-1.9.2-p180/gems/muri-1.1.6/lib/muri/base.rb:40:in `initialize'
    from /Users/onesup/.rvm/gems/ruby-1.9.2-p180/gems/muri-1.1.6/lib/muri/base.rb:30:in`new'
    from /Users/onesup/.rvm/gems/ruby-1.9.2-p180/gems/muri-1.1.6/lib/muri/base.rb:30:in `parse'
    from (irb):13
    from /Users/onesup/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands/console.rb:44:in`start'
    from /Users/onesup/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands/console.rb:8:in `start'
    from /Users/onesup/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands.rb:23:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by bananastalktome** [comment]
Sorry for this issue, we use ruby 1.9.1, and this issue only seems to present itself with 1.9.2 . The newest version of the gem should fix this bug. Thanks for pointing it out to me, and submit any additional issues you may find.
